### ISSUE TITLE
Marinara recipe is too boring

### ISSUE THREAD

**Issue by k88hudson** [k88hudson/pastamatic#1]
Maybe could we add some aromatics? Onions? Pepper? Something?

**Comment by claireabbott** [comment]
I can help

**Comment by k88hudson** [comment]
Awesome, thanks @claireabbott! Please go ahead 🔥 💃 🐱

**Comment by k88hudson** [comment]
This issue was closed by https://github.com/k88hudson/pastamatic/commit/6a295da2f67a2c5066fbc5b52284b87b93f5d4a4
